version: "3"

# Volumes 🧰
volumes:
  redpanda: null

# Services 💪
services:
  # Redpanda ⚡
  redpanda:
    image: vectorized/redpanda:v22.2.2

    container_name: redpanda

    volumes:
      - redpanda:/var/lib/redpanda/data

    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      - --advertise-kafka-addr INTERNAL://redpanda:29092,EXTERNAL://localhost:9092

    ports:
      - "9092:9092"
      - "29092:29092"
